=== swlegion/stardust/data/schema/unit.json
{
  "$id": "https://schema.swlegion.dev/unit.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "title": "Unit",
  "type": "object",

  "additionalProperties": false,

  "properties": {
    "card": {
      "description": "A relative URI to the card image.",
      "type": "string",
      "pattern": "(.*?)\\.(png|jpg)$",
      "format": "uri-reference"
    },
    "faction": {
      "description": "Which faction does this unit belongs to.",
      "type": "string",
      "enum": [
        "Galactic Empire",
        "Galactic Republic",
        "Rebel Alliance",
        "Separatist Alliance"
      ]
    },
    "name": {
      "description": "The unit's full name as printed on the card.",
      "type": "string"
    },
    "rank": {
      "description": "Rank of the unit used for list building and orders.",
      "type": "string",
      "enum": [
        "Commander",
        "Operative",
        "Counterpart",
        "Corps",
        "Special Forces",
        "Support",
        "Heavy"
      ]
    },
    "speed": {
      "description": "Maximum speed of the unit.",
      "type": "integer",
      "enum": [0, 1, 2, 3],
      "default": 2
    },
    "size": {
      "$ref": "./bases.json#/definitions/size"
    },
    "title": {
      "description": "Title of the unit card, if any.",
      "type": "string"
    },
    "models": {
      "description": "Model information for this unit. Optional.",
      "type": "array",
      "items": { "$ref": "./model.json" },
      "default": []
    }
  },

  "required": ["card", "faction", "name", "rank", "size", "speed"]
}

=== swlegion/stardust/data/unit/rebel-alliance/corps/rebel-troopers.json
{
  "card": "./rebel-troopers/card.png",
  "faction": "Rebel Alliance",
  "rank": "Corps",
  "name": "Rebel Troopers",
  "size": "Small",
  "speed": 2,
  "models": [
    {
      "render": "./rebel-troopers/1.obj",
      "texture": "./rebel-troopers/leader.jpg"
    },
    {
      "render": "./rebel-troopers/2.obj",
      "texture": "./rebel-troopers/generic.jpg"
    },
    {
      "render": "./rebel-troopers/3.obj",
      "texture": "./rebel-troopers/generic.jpg"
    },
    {
      "render": "./rebel-troopers/4.obj",
      "texture": "./rebel-troopers/generic.jpg"
    }
  ]
}
